# Generated by Django 4.2.1 on 2023-06-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplo',
            name='number',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
