# Generated by Django 4.2.1 on 2023-06-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ejemplo_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('nameCuidador', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('tel', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePaciente', models.CharField(max_length=25, unique=True)),
                ('especie', models.CharField(max_length=25)),
                ('edad', models.IntegerField(max_length=3)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Ejemplo',
        ),
    ]
