# Generated by Django 4.2.1 on 2023-06-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_carrito_cliente_producto_delete_cita_delete_cuidador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='precio',
            new_name='precio_Total',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_Producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='provedor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='carrito_cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='carrito_producto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Barrio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name_cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name_producto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
