# Generated by Django 4.2.1 on 2023-06-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_precio_carrito_precio_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='carrito_producto',
            new_name='carritoproducto',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name_cliente',
            new_name='namecliente',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='name_producto',
            new_name='nameproducto',
        ),
    ]
