# Generated by Django 4.2.1 on 2023-06-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_carrito_producto_carrito_carritoproducto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='precio_Total',
            new_name='precioTotal',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='carrito_cliente',
        ),
        migrations.AddField(
            model_name='carrito',
            name='carritocliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cliente'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='carritoproducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Barrio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='namecliente',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nameproducto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='provedor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
