# Generated by Django 4.2.1 on 2023-06-17 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_precio_total_carrito_preciototal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameCategoria', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='carritocliente',
            new_name='carritoCliente',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='carritoproducto',
            new_name='carritoProducto',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='namecliente',
            new_name='nameCliente',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nameproducto',
            new_name='nameProducto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_compra',
            new_name='precioCompra',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_venta',
            new_name='precioVenta',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='provedor',
            new_name='proveedor',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='carrito',
            name='carritoCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.categoria'),
        ),
    ]
