# Generated by Django 4.2.1 on 2023-06-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='', upload_to='imagesProducto/'),
        ),
    ]
