# Generated by Django 4.2.1 on 2023-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='desProducto',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
    ]
